"""Convert the SimplyRetro D8 STEP asset into OpenSCAD code."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import List, Tuple

from generators.openscad_framework import OpenSCAD, OpenSCADScript

try:  # pragma: no cover - optional dependency
    import cadquery as cq
except ImportError:  # pragma: no cover - handled at runtime
    cq = None  # type: ignore[assignment]


@dataclass(slots=True)
class TessellationSettings:
    """Parameters used while tessellating the STEP geometry."""

    angular_tolerance: float = 0.2
    linear_tolerance: float = 0.5
    min_volume: float = 50_000.0
    precision: int = 4
    module_name: str = "simplyretro_d8"


class SimplyRetroD8Generator:
    """Generate OpenSCAD for the archived SimplyRetro D8 die."""

    def __init__(
        self,
        step_path: str | Path | None = None,
        settings: TessellationSettings | None = None,
    ) -> None:
        self.step_path = Path(step_path or Path("assets") / "simplyRetro D8.step")
        self.settings = settings or TessellationSettings()

    def generate_scad(self) -> str:
        """Return the OpenSCAD document reconstructed from the STEP file."""

        vertices, faces = self._build_polyhedron_data()
        body = OpenSCAD.polyhedron(vertices, faces, convexity=10)

        script = OpenSCADScript()
        script.add_header("// Generated by SimplyRetroD8Generator")
        script.add_header(f"// Source STEP: {self.step_path}")
        script.add_header(
            "// Tessellation: angular=%.3f linear=%.3f min_volume=%.1f" % (
                self.settings.angular_tolerance,
                self.settings.linear_tolerance,
                self.settings.min_volume,
            )
        )
        script.define_module(self.settings.module_name, body)
        script.add_body(OpenSCAD.module_call(self.settings.module_name))
        return script.render()

    def save_scad(self, destination: str | Path) -> Path:
        """Persist the generated OpenSCAD file to ``destination``."""

        path = Path(destination)
        path.write_text(self.generate_scad(), encoding="utf-8")
        return path

    def _build_polyhedron_data(self) -> Tuple[List[List[float]], List[List[int]]]:
        backend = self._require_cadquery()
        assembly = backend.importers.importStep(str(self.step_path))
        solids = list(assembly.solids())
        if not solids:
            raise RuntimeError(
                f"No solids were found inside {self.step_path!s}."
            )

        selected = [solid for solid in solids if solid.Volume() >= self.settings.min_volume]
        if not selected:
            selected = solids

        compound = backend.Compound.makeCompound(selected)
        vectors, faces = compound.tessellate(
            self.settings.angular_tolerance,
            self.settings.linear_tolerance,
        )

        vertices = [
            [
                round(vector.x, self.settings.precision),
                round(vector.y, self.settings.precision),
                round(vector.z, self.settings.precision),
            ]
            for vector in vectors
        ]
        face_indices = [list(face) for face in faces]
        return vertices, face_indices

    @staticmethod
    def _require_cadquery():
        if cq is None:  # pragma: no cover - exercised when dependency missing
            raise ModuleNotFoundError(
                "cadquery is required to convert the STEP file. Install it via 'pip install cadquery'."
            )
        return cq


def _build_arg_parser() -> "argparse.ArgumentParser":  # pragma: no cover - CLI glue
    import argparse

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--step",
        type=Path,
        default=Path("assets") / "simplyRetro D8.step",
        help="Path to the SimplyRetro D8 STEP asset.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("simplyretro_d8.scad"),
        help="Destination OpenSCAD file.",
    )
    parser.add_argument(
        "--min-volume",
        type=float,
        default=TessellationSettings.min_volume,
        help="Minimum solid volume to include (mm^3).",
    )
    parser.add_argument(
        "--angular",
        type=float,
        default=TessellationSettings.angular_tolerance,
        help="Angular tessellation tolerance.",
    )
    parser.add_argument(
        "--linear",
        type=float,
        default=TessellationSettings.linear_tolerance,
        help="Linear tessellation tolerance.",
    )
    parser.add_argument(
        "--precision",
        type=int,
        default=TessellationSettings.precision,
        help="Decimal precision for vertex coordinates.",
    )
    parser.add_argument(
        "--module",
        type=str,
        default=TessellationSettings.module_name,
        help="Name of the OpenSCAD module to generate.",
    )
    return parser


def main() -> None:  # pragma: no cover - CLI glue
    parser = _build_arg_parser()
    args = parser.parse_args()

    settings = TessellationSettings(
        angular_tolerance=args.angular,
        linear_tolerance=args.linear,
        min_volume=args.min_volume,
        precision=args.precision,
        module_name=args.module,
    )
    generator = SimplyRetroD8Generator(step_path=args.step, settings=settings)
    output_path = generator.save_scad(args.output)
    print(f"Saved OpenSCAD file to {output_path}")


if __name__ == "__main__":  # pragma: no cover - CLI entry point
    main()


__all__ = ["SimplyRetroD8Generator", "TessellationSettings"]
