"""Procedurally generate an OpenSCAD teapot model."""

from __future__ import annotations

from dataclasses import dataclass
from typing import List, Sequence

from generators.openscad_framework import OpenSCAD, OpenSCADScript

__all__ = ["TeapotGenerator", "TeapotDimensions"]


@dataclass
class TeapotDimensions:
    """Dimension presets for the procedural teapot."""

    body_radius: float = 30.0
    body_height: float = 42.0
    wall_thickness: float = 2.4
    lid_height: float = 11.0
    knob_height: float = 5.0
    knob_radius: float = 3.5
    spout_length: float = 30.0
    spout_radius: float = 4.2
    spout_tilt: float = 20.0
    handle_thickness: float = 3.8
    handle_gap: float = 8.0


class TeapotGenerator:
    """Create a teapot using the reusable OpenSCAD framework."""

    def __init__(
        self,
        dimensions: TeapotDimensions | None = None,
        segments: int = 96,
    ) -> None:
        self.dim = dimensions or TeapotDimensions()
        self.segments = segments

    def generate_scad(self) -> str:
        """Return the full OpenSCAD document for the teapot."""

        script = OpenSCADScript()
        script.add_header("// Generated by TeapotGenerator")
        script.add_header("// Dimensions: " + str(self.dim))

        script.define_module("teapot_body", self._build_body())
        script.define_module("teapot_lid", self._build_lid())
        script.define_module("teapot_spout", self._build_spout())
        script.define_module("teapot_handle", self._build_handle())

        body = OpenSCAD.module_call("teapot_body")
        lid = OpenSCAD.module_call("teapot_lid")
        spout = OpenSCAD.module_call("teapot_spout")
        handle = OpenSCAD.module_call("teapot_handle")

        script.define_module("teapot", body.union(lid, spout, handle))
        script.add_body(OpenSCAD.module_call("teapot"))
        return script.render()

    def save_scad(self, filename: str) -> None:
        """Persist the generated script to ``filename``."""

        with open(filename, "w", encoding="utf-8") as handle:
            handle.write(self.generate_scad())

    def _build_body(self) -> OpenSCAD:
        dim = self.dim
        outer_profile = self._close_profile([
            (0, 0),
            (dim.body_radius * 0.95, 0),
            (dim.body_radius + 3.0, dim.body_height * 0.25),
            (dim.body_radius + 1.5, dim.body_height * 0.6),
            (dim.body_radius * 0.65, dim.body_height),
            (0, dim.body_height),
        ])

        inner_profile = self._close_profile([
            (dim.wall_thickness, dim.wall_thickness),
            (dim.body_radius - dim.wall_thickness, dim.wall_thickness),
            (dim.body_radius - dim.wall_thickness, dim.body_height * 0.7),
            (dim.body_radius * 0.55, dim.body_height - dim.wall_thickness),
            (dim.wall_thickness, dim.body_height - dim.wall_thickness),
        ])

        outer = OpenSCAD.polygon(outer_profile).rotate_extrude(
            convexity=10,
            segments=self.segments,
        )

        inner = OpenSCAD.polygon(inner_profile).rotate_extrude(
            convexity=10,
            segments=self.segments,
        ).translate([0, 0, dim.wall_thickness])

        rim = OpenSCAD.cylinder(
            h=dim.wall_thickness * 1.4,
            r=dim.body_radius + 0.6,
        ).translate([0, 0, dim.body_height - dim.wall_thickness])

        return outer.difference(inner).union(rim)

    def _build_lid(self) -> OpenSCAD:
        dim = self.dim
        lid_profile = self._close_profile([
            (dim.wall_thickness * 0.75, 0),
            (dim.body_radius * 0.7, 0),
            (dim.body_radius * 0.55, dim.lid_height * 0.5),
            (dim.body_radius * 0.7, dim.lid_height),
            (dim.wall_thickness * 0.75, dim.lid_height),
        ])

        lid_inner = self._close_profile([
            (dim.wall_thickness * 1.3, dim.wall_thickness),
            (dim.body_radius * 0.62, dim.wall_thickness),
            (dim.body_radius * 0.5, dim.lid_height * 0.7),
            (dim.wall_thickness * 1.3, dim.lid_height * 0.9),
        ])

        outer = OpenSCAD.polygon(lid_profile).rotate_extrude(
            convexity=8,
            segments=self.segments,
        ).translate([0, 0, dim.body_height - dim.wall_thickness / 2])

        inner = OpenSCAD.polygon(lid_inner).rotate_extrude(
            convexity=6,
            segments=self.segments,
        ).translate([0, 0, dim.body_height])

        knob = OpenSCAD.cylinder(
            h=dim.knob_height,
            r=dim.knob_radius,
        ).translate([0, 0, dim.body_height + dim.lid_height])

        return outer.difference(inner).union(knob)

    def _build_spout(self) -> OpenSCAD:
        dim = self.dim
        base_height = dim.body_height * 0.62
        base_offset = dim.body_radius + dim.wall_thickness

        outer = OpenSCAD.cylinder(
            h=dim.spout_length,
            r=dim.spout_radius,
        ).rotate([0, 90, 0]).rotate(a=-dim.spout_tilt, v=[0, 1, 0]).translate([
            base_offset,
            0,
            base_height,
        ])

        inner = OpenSCAD.cylinder(
            h=dim.spout_length + 1.5,
            r=max(dim.spout_radius - dim.wall_thickness * 0.6, 0.8),
        ).rotate([0, 90, 0]).rotate(a=-dim.spout_tilt, v=[0, 1, 0]).translate([
            base_offset + 0.5,
            0,
            base_height + 0.5,
        ])

        flare = OpenSCAD.cylinder(
            h=dim.wall_thickness * 2.2,
            r=dim.spout_radius + 1.2,
        ).translate([
            base_offset + dim.spout_length * 0.45,
            0,
            base_height + dim.spout_length * 0.25,
        ])

        return outer.union(flare).difference(inner)

    def _build_handle(self) -> OpenSCAD:
        dim = self.dim
        radius = dim.body_radius + dim.handle_gap
        top = OpenSCAD.sphere(dim.handle_thickness).translate([
            -radius,
            0,
            dim.body_height * 0.85,
        ])

        middle = OpenSCAD.sphere(dim.handle_thickness).translate([
            -radius - dim.handle_thickness,
            0,
            dim.body_height * 0.6,
        ])

        bottom = OpenSCAD.sphere(dim.handle_thickness).translate([
            -radius,
            0,
            dim.body_height * 0.35,
        ])

        grip = top.hull(middle, bottom)
        grip = grip.union(
            OpenSCAD.cylinder(
                h=dim.handle_thickness * 2,
                r=dim.handle_thickness,
            ).translate([
                -radius,
                0,
                dim.body_height * 0.35,
            ])
        )
        return grip

    @staticmethod
    def _close_profile(
        points: Sequence[Sequence[float]],
    ) -> List[Sequence[float]]:
        if not points:
            return []
        if points[0] == points[-1]:
            return list(points)
        closed = list(points)
        closed.append(points[0])
        return closed


if __name__ == "__main__":
    generator = TeapotGenerator()
    generator.save_scad("teapot.scad")
